FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:c64e0d04e42a0ab615300d9579adaa775480f65d3b632f2272e8cd56e7d2f194 AS runtime

RUN npm install -g \
        @biomejs/biome \
        deno \
    && npm cache clean --force

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/devcontainers
