FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:e25a761ebfdcb8c2fa25b34a3a0c32b656b0ae02a049dc9f536074ab7b38d6c9 AS runtime

RUN npm install -g \
        @biomejs/biome \
        deno \
    && npm cache clean --force

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/devcontainers
