FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:2d6f17392f74ecbceb2b59d303021f698555961ad807c353272bff123413f83d AS runtime

RUN npm install -g \
        @biomejs/biome \
        deno \
    && npm cache clean --force

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/devcontainers
