FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:a3b2dc4887415c1d0317428f2431ca4f4318fa6620b95ad014e1c5820b934596 AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends rustup \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER dev

RUN rustup toolchain install stable \
    && rustup default stable \
    && rustup component add rust-analyzer rust-src

USER root

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/devcontainers
