FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:2d6f17392f74ecbceb2b59d303021f698555961ad807c353272bff123413f83d AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        golang \
        gopls \
        golang-mvdan-gofumpt-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/devcontainers
