FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:e25a761ebfdcb8c2fa25b34a3a0c32b656b0ae02a049dc9f536074ab7b38d6c9 AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        golang \
        gopls \
        golang-mvdan-gofumpt-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/devcontainers
