FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:c64e0d04e42a0ab615300d9579adaa775480f65d3b632f2272e8cd56e7d2f194 AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        clang \
        clang-format \
        clang-tidy \
        clangd \
        cmake \
        lld \
        llvm \
        ninja-build \
        pkgconf \
        valgrind \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/devcontainers
