FROM ghcr.io/christoffercarlsson/node@sha256:21429f5e718622987c721184831e4887672b40d0a7fb1cea79ac5b9b133c712a AS node-tools-builder

RUN npm install -g --ignore-scripts \
    bash-language-server \
    @earendil-works/pi-coding-agent \
    tombi

RUN npm install -g @anthropic-ai/claude-code

FROM ghcr.io/christoffercarlsson/rust@sha256:1e72e85d9f58cdced1d96db92640d35a7c795374f91609baa27afd3cdc73b80a AS rust-tools-builder

RUN cargo install --root /usr/local \
    bat \
    fd-find \
    jaq \
    proximity-sort \
    ripgrep \
    rumdl \
    tokei

FROM ghcr.io/christoffercarlsson/lua-language-server@sha256:6ef86823e6413531996ca59afab60c50bb4042b3dbf9680c0aac399cad7c1f5f AS luals-builder

FROM ghcr.io/christoffercarlsson/debian-neovim@sha256:3371e13da6d8079c96ea308604dd407c14053c11d0b0b7ba85f7947f62b0cb58 AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && rm -f /etc/dpkg/dpkg.cfg.d/docker \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        fish \
        fzf \
        git \
        gnupg \
        jq \
        less \
        man-db \
        manpages \
        manpages-dev \
        openssh-server \
        shfmt \
        stow \
        tmux \
        zsh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/entrypoint /usr/local/sbin/entrypoint
COPY configs/sshd.conf /etc/ssh/sshd_config.d/devcontainer.conf

COPY --from=node-tools-builder /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node-tools-builder /usr/local/bin /usr/local/bin

COPY --from=rust-tools-builder /usr/local/bin/ /usr/local/bin/

COPY --from=luals-builder /opt/lua-language-server /opt/lua-language-server
COPY --from=luals-builder /usr/local/bin/lua-language-server /usr/local/bin/lua-language-server

RUN groupadd --gid 1000 dev \
    && useradd --uid 1000 --gid dev --shell /bin/zsh --create-home dev \
    && install -o dev -g dev -d /workspace

USER dev
WORKDIR /home/dev

COPY --chown=dev:dev scripts/bash /home/dev/.bash.local
COPY --chown=dev:dev scripts/fish /home/dev/.fish.local
COPY --chown=dev:dev scripts/zsh /home/dev/.zsh.local

RUN rm .bashrc

RUN git clone https://github.com/christoffercarlsson/dotfiles .dotfiles \
    && cd .dotfiles \
    && stow bash \
        biome \
        claude \
        fish \
        git \
        neovim \
        pi \
        rumdl \
        scripts \
        tmux \
        vim \
        zsh

USER root
WORKDIR /workspace

EXPOSE 22

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/devcontainers
